# Generated by Django 4.0.4 on 2022-04-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='itemCount',
        ),
    ]
