# Generated by Django 4.0.4 on 2022-04-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_product_description_remove_product_itemcount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated', ['-created']]},
        ),
    ]
