# Generated by Django 4.0.4 on 2022-04-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
